### ISSUE TITLE
NVIDIAのJetsonNANOとGreengrass/SageMaker/RoboMakerの話

### ISSUE THREAD

**Issue by txracing** [aws-events/aws-dev-day-online-japan-2021-cfp#60]
### イベント登録規約、AWS 行動規範 Code of Conduct への同意 (必須)

- [X] 私は、[イベント登録規約](https://aws.amazon.com/jp/events/terms/)、および [AWS 行動規範 Code of Conduct](https://aws.amazon.com/jp/codeofconduct/) を確認し、同意しました

### Twitter ID (必須)

TxRacing

### セッションタイトル (必須)

- [X] セッションのタイトルをイシュー件名に最大40文字程度で入力しました

### セッションのアブストラクト (最大250文字) (必須)

前半はNVIDIAのJetsonNANOというエッジデバイスを使いAWS IoT Greengrass Core V2 の導入設定とSageMakerでの画像認識をデモします（AWSのblog記事にある)。記事上で書かれていない細かいJetsonNANO特有のTIPSとGreengrass導入時に気を付けるべき点を紹介します。後半はNVIDIAのJetbotの紹介、RoboMakerとROSの関連性と実際にRoboMakerを動作させるところまで紹介します。

### セッションについての補足情報 (最大800文字) (任意)

一部ライブデモを行いますが、時間に収まるように事前に収録する可能性があります。

### 想定受講者の知識レベル（必須）

初級 - セッションの中心となるトピックについての具体的な知識がない方、これから勉強しようと考えている方向け

### 想定受講者の開発対象やロール・役割 (複数選択可) (必須)

機械学習モデル開発

### 想定受講者の業種・業界・業態 (複数選択可) (任意)

エンタープライズ

### セッションのトピック (複数選択可) (必須)

アプリケーションアーキテクチャー

### セッションの技術カテゴリー (複数選択可) (必須)

コンテナ, AI / 機械学習, IoT, ロボティクス

### セッション内で登場する主な AWS サービス (任意)

Greengrass, SageMaker, RoboMaker, Kinesis Video Streams

**Comment by ssugimoto** [comment]
残念です
thats too bad.
